// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddEvaluations implements addEvaluations operation.
	//
	// Add span, trace, or document evaluations.
	//
	// POST /v1/evaluations
	AddEvaluations(ctx context.Context, req AddEvaluationsReq, params AddEvaluationsParams) (AddEvaluationsRes, error)
	// AnnotateSessions implements annotateSessions operation.
	//
	// Create session annotations.
	//
	// POST /v1/session_annotations
	AnnotateSessions(ctx context.Context, req *AnnotateSessionsRequestBody, params AnnotateSessionsParams) (AnnotateSessionsRes, error)
	// AnnotateSpanDocuments implements annotateSpanDocuments operation.
	//
	// Annotate Span Documents.
	//
	// POST /v1/document_annotations
	AnnotateSpanDocuments(ctx context.Context, req *AnnotateSpanDocumentsRequestBody, params AnnotateSpanDocumentsParams) (AnnotateSpanDocumentsRes, error)
	// AnnotateSpans implements annotateSpans operation.
	//
	// Create span annotations.
	//
	// POST /v1/span_annotations
	AnnotateSpans(ctx context.Context, req *AnnotateSpansRequestBody, params AnnotateSpansParams) (AnnotateSpansRes, error)
	// AnnotateTraces implements annotateTraces operation.
	//
	// Create trace annotations.
	//
	// POST /v1/trace_annotations
	AnnotateTraces(ctx context.Context, req *AnnotateTracesRequestBody, params AnnotateTracesParams) (AnnotateTracesRes, error)
	// CreateAnnotationConfigV1AnnotationConfigsPost implements create_annotation_config_v1_annotation_configs_post operation.
	//
	// Create an annotation configuration.
	//
	// POST /v1/annotation_configs
	CreateAnnotationConfigV1AnnotationConfigsPost(ctx context.Context, req CreateAnnotationConfigData) (CreateAnnotationConfigV1AnnotationConfigsPostRes, error)
	// CreateExperiment implements createExperiment operation.
	//
	// Create experiment on a dataset.
	//
	// POST /v1/datasets/{dataset_id}/experiments
	CreateExperiment(ctx context.Context, req *CreateExperimentRequestBody, params CreateExperimentParams) (CreateExperimentRes, error)
	// CreateExperimentRun implements createExperimentRun operation.
	//
	// Create run for an experiment.
	//
	// POST /v1/experiments/{experiment_id}/runs
	CreateExperimentRun(ctx context.Context, req *CreateExperimentRunRequestBody, params CreateExperimentRunParams) (CreateExperimentRunRes, error)
	// CreateProject implements createProject operation.
	//
	// Create a new project with the specified configuration.
	//
	// POST /v1/projects
	CreateProject(ctx context.Context, req *CreateProjectRequestBody) (CreateProjectRes, error)
	// CreatePromptVersionTag implements createPromptVersionTag operation.
	//
	// Add a new tag to a specific prompt version. Tags help identify and categorize different versions
	// of a prompt.
	//
	// POST /v1/prompt_versions/{prompt_version_id}/tags
	CreatePromptVersionTag(ctx context.Context, req *PromptVersionTagData, params CreatePromptVersionTagParams) (CreatePromptVersionTagRes, error)
	// CreateSpanNote implements createSpanNote operation.
	//
	// Add a note annotation to a span. Notes are special annotations that allow multiple entries per
	// span (unlike regular annotations which are unique by name and identifier). Each note gets a unique
	// timestamp-based identifier.
	//
	// POST /v1/span_notes
	CreateSpanNote(ctx context.Context, req *CreateSpanNoteRequestBody) (CreateSpanNoteRes, error)
	// CreateSpans implements createSpans operation.
	//
	// Submit spans to be inserted into a project. If any spans are invalid or duplicates, no spans will
	// be inserted.
	//
	// POST /v1/projects/{project_identifier}/spans
	CreateSpans(ctx context.Context, req *CreateSpansRequestBody, params CreateSpansParams) (CreateSpansRes, error)
	// CreateUser implements createUser operation.
	//
	// Create a new user with the specified configuration.
	//
	// POST /v1/users
	CreateUser(ctx context.Context, req *CreateUserRequestBody) (CreateUserRes, error)
	// DeleteAnnotationConfigV1AnnotationConfigsConfigIDDelete implements delete_annotation_config_v1_annotation_configs__config_id__delete operation.
	//
	// Delete an annotation configuration.
	//
	// DELETE /v1/annotation_configs/{config_id}
	DeleteAnnotationConfigV1AnnotationConfigsConfigIDDelete(ctx context.Context, params DeleteAnnotationConfigV1AnnotationConfigsConfigIDDeleteParams) (DeleteAnnotationConfigV1AnnotationConfigsConfigIDDeleteRes, error)
	// DeleteDatasetById implements deleteDatasetById operation.
	//
	// Delete dataset by ID.
	//
	// DELETE /v1/datasets/{id}
	DeleteDatasetById(ctx context.Context, params DeleteDatasetByIdParams) (DeleteDatasetByIdRes, error)
	// DeleteExperiment implements deleteExperiment operation.
	//
	// Delete experiment by ID.
	//
	// DELETE /v1/experiments/{experiment_id}
	DeleteExperiment(ctx context.Context, params DeleteExperimentParams) (DeleteExperimentRes, error)
	// DeleteProject implements deleteProject operation.
	//
	// Delete an existing project and all its associated data. The project identifier is either project
	// ID or project name. The default project cannot be deleted. Note: When using a project name as the
	// identifier, it cannot contain slash (/), question mark (?), or pound sign (#) characters.
	//
	// DELETE /v1/projects/{project_identifier}
	DeleteProject(ctx context.Context, params DeleteProjectParams) (DeleteProjectRes, error)
	// DeleteSpan implements deleteSpan operation.
	//
	// Delete a single span by identifier.
	// **Important**: This operation deletes ONLY the specified span itself and does NOT
	// delete its descendants/children. All child spans will remain in the trace and
	// become orphaned (their parent_id will point to a non-existent span).
	// Behavior:
	// - Deletes only the target span (preserves all descendant spans)
	// - If this was the last span in the trace, the trace record is also deleted
	// - If the deleted span had a parent, its cumulative metrics (error count, token counts)
	// are subtracted from all ancestor spans in the chain
	// **Note**: This operation is irreversible and may create orphaned spans.
	//
	// DELETE /v1/spans/{span_identifier}
	DeleteSpan(ctx context.Context, params DeleteSpanParams) (DeleteSpanRes, error)
	// DeleteTrace implements deleteTrace operation.
	//
	// Delete an entire trace by its identifier. The identifier can be either:
	// 1. A Relay node ID (base64-encoded)
	// 2. An OpenTelemetry trace_id (hex string)
	// This will permanently remove all spans in the trace and their associated data.
	//
	// DELETE /v1/traces/{trace_identifier}
	DeleteTrace(ctx context.Context, params DeleteTraceParams) (DeleteTraceRes, error)
	// DeleteUser implements deleteUser operation.
	//
	// Delete an existing user by their unique GlobalID.
	//
	// DELETE /v1/users/{user_id}
	DeleteUser(ctx context.Context, params DeleteUserParams) (DeleteUserRes, error)
	// GetAnnotationConfigByNameOrIDV1AnnotationConfigsConfigIdentifierGet implements get_annotation_config_by_name_or_id_v1_annotation_configs__config_identifier__get operation.
	//
	// Get an annotation configuration by ID or name.
	//
	// GET /v1/annotation_configs/{config_identifier}
	GetAnnotationConfigByNameOrIDV1AnnotationConfigsConfigIdentifierGet(ctx context.Context, params GetAnnotationConfigByNameOrIDV1AnnotationConfigsConfigIdentifierGetParams) (GetAnnotationConfigByNameOrIDV1AnnotationConfigsConfigIdentifierGetRes, error)
	// GetDataset implements getDataset operation.
	//
	// Get dataset by ID.
	//
	// GET /v1/datasets/{id}
	GetDataset(ctx context.Context, params GetDatasetParams) (GetDatasetRes, error)
	// GetDatasetCsv implements getDatasetCsv operation.
	//
	// Download dataset examples as CSV file.
	//
	// GET /v1/datasets/{id}/csv
	GetDatasetCsv(ctx context.Context, params GetDatasetCsvParams) (GetDatasetCsvRes, error)
	// GetDatasetExamples implements getDatasetExamples operation.
	//
	// Get examples from a dataset.
	//
	// GET /v1/datasets/{id}/examples
	GetDatasetExamples(ctx context.Context, params GetDatasetExamplesParams) (GetDatasetExamplesRes, error)
	// GetDatasetJSONLOpenAIEvals implements getDatasetJSONLOpenAIEvals operation.
	//
	// Download dataset examples as OpenAI evals JSONL file.
	//
	// GET /v1/datasets/{id}/jsonl/openai_evals
	GetDatasetJSONLOpenAIEvals(ctx context.Context, params GetDatasetJSONLOpenAIEvalsParams) (GetDatasetJSONLOpenAIEvalsRes, error)
	// GetDatasetJSONLOpenAIFineTuning implements getDatasetJSONLOpenAIFineTuning operation.
	//
	// Download dataset examples as OpenAI fine-tuning JSONL file.
	//
	// GET /v1/datasets/{id}/jsonl/openai_ft
	GetDatasetJSONLOpenAIFineTuning(ctx context.Context, params GetDatasetJSONLOpenAIFineTuningParams) (GetDatasetJSONLOpenAIFineTuningRes, error)
	// GetEvaluations implements getEvaluations operation.
	//
	// Get span, trace, or document evaluations from a project.
	//
	// GET /v1/evaluations
	GetEvaluations(ctx context.Context, params GetEvaluationsParams) (GetEvaluationsRes, error)
	// GetExperiment implements getExperiment operation.
	//
	// Get experiment by ID.
	//
	// GET /v1/experiments/{experiment_id}
	GetExperiment(ctx context.Context, params GetExperimentParams) (GetExperimentRes, error)
	// GetExperimentCSV implements getExperimentCSV operation.
	//
	// Download experiment runs as a CSV file.
	//
	// GET /v1/experiments/{experiment_id}/csv
	GetExperimentCSV(ctx context.Context, params GetExperimentCSVParams) (GetExperimentCSVRes, error)
	// GetExperimentJSON implements getExperimentJSON operation.
	//
	// Download experiment runs as a JSON file.
	//
	// GET /v1/experiments/{experiment_id}/json
	GetExperimentJSON(ctx context.Context, params GetExperimentJSONParams) (GetExperimentJSONRes, error)
	// GetIncompleteExperimentEvaluations implements getIncompleteExperimentEvaluations operation.
	//
	// Get experiment runs that have incomplete evaluations.
	// Returns runs with:
	// - Missing evaluations (evaluator has not been run)
	// - Failed evaluations (evaluator ran but has errors)
	// Args:
	// experiment_id: The ID of the experiment
	// evaluation_name: List of evaluation names to check (required, at least one)
	// cursor: Cursor for pagination
	// limit: Maximum number of results to return
	// Returns:
	// Paginated list of runs with incomplete evaluations.
	//
	// GET /v1/experiments/{experiment_id}/incomplete-evaluations
	GetIncompleteExperimentEvaluations(ctx context.Context, params GetIncompleteExperimentEvaluationsParams) (GetIncompleteExperimentEvaluationsRes, error)
	// GetIncompleteExperimentRuns implements getIncompleteExperimentRuns operation.
	//
	// Get runs that need to be completed for this experiment.
	// Returns all incomplete runs, including both missing runs (not yet attempted)
	// and failed runs (attempted but have errors).
	// Args:
	// experiment_id: The ID of the experiment
	// cursor: Cursor for pagination
	// limit: Maximum number of results to return
	// Returns:
	// Paginated list of incomplete runs grouped by dataset example,
	// with repetition numbers that need to be run.
	//
	// GET /v1/experiments/{experiment_id}/incomplete-runs
	GetIncompleteExperimentRuns(ctx context.Context, params GetIncompleteExperimentRunsParams) (GetIncompleteExperimentRunsRes, error)
	// GetProject implements getProject operation.
	//
	// Retrieve a specific project using its unique identifier: either project ID or project name. Note:
	// When using a project name as the identifier, it cannot contain slash (/), question mark (?), or
	// pound sign (#) characters.
	//
	// GET /v1/projects/{project_identifier}
	GetProject(ctx context.Context, params GetProjectParams) (GetProjectRes, error)
	// GetProjects implements getProjects operation.
	//
	// Retrieve a paginated list of all projects in the system.
	//
	// GET /v1/projects
	GetProjects(ctx context.Context, params GetProjectsParams) (GetProjectsRes, error)
	// GetPromptVersionByPromptVersionId implements getPromptVersionByPromptVersionId operation.
	//
	// Retrieve a specific prompt version using its unique identifier. A prompt version contains the
	// actual template and configuration.
	//
	// GET /v1/prompt_versions/{prompt_version_id}
	GetPromptVersionByPromptVersionId(ctx context.Context, params GetPromptVersionByPromptVersionIdParams) (GetPromptVersionByPromptVersionIdRes, error)
	// GetPromptVersionByTagName implements getPromptVersionByTagName operation.
	//
	// Retrieve a specific prompt version using its tag name. Tags are used to identify specific versions
	// of a prompt.
	//
	// GET /v1/prompts/{prompt_identifier}/tags/{tag_name}
	GetPromptVersionByTagName(ctx context.Context, params GetPromptVersionByTagNameParams) (GetPromptVersionByTagNameRes, error)
	// GetPromptVersionLatest implements getPromptVersionLatest operation.
	//
	// Retrieve the most recent version of a specific prompt.
	//
	// GET /v1/prompts/{prompt_identifier}/latest
	GetPromptVersionLatest(ctx context.Context, params GetPromptVersionLatestParams) (GetPromptVersionLatestRes, error)
	// GetPromptVersionTags implements getPromptVersionTags operation.
	//
	// Retrieve all tags associated with a specific prompt version. Tags are used to identify and
	// categorize different versions of a prompt.
	//
	// GET /v1/prompt_versions/{prompt_version_id}/tags
	GetPromptVersionTags(ctx context.Context, params GetPromptVersionTagsParams) (GetPromptVersionTagsRes, error)
	// GetPrompts implements getPrompts operation.
	//
	// Retrieve a paginated list of all prompts in the system. A prompt can have multiple versions.
	//
	// GET /v1/prompts
	GetPrompts(ctx context.Context, params GetPromptsParams) (GetPromptsRes, error)
	// GetSpans implements getSpans operation.
	//
	// Return spans within a project filtered by time range. Supports cursor-based pagination.
	//
	// GET /v1/projects/{project_identifier}/spans
	GetSpans(ctx context.Context, params GetSpansParams) (GetSpansRes, error)
	// GetUsers implements getUsers operation.
	//
	// Retrieve a paginated list of all users in the system.
	//
	// GET /v1/users
	GetUsers(ctx context.Context, params GetUsersParams) (GetUsersRes, error)
	// ListAnnotationConfigsV1AnnotationConfigsGet implements list_annotation_configs_v1_annotation_configs_get operation.
	//
	// Retrieve a paginated list of all annotation configurations in the system.
	//
	// GET /v1/annotation_configs
	ListAnnotationConfigsV1AnnotationConfigsGet(ctx context.Context, params ListAnnotationConfigsV1AnnotationConfigsGetParams) (ListAnnotationConfigsV1AnnotationConfigsGetRes, error)
	// ListDatasetVersionsByDatasetId implements listDatasetVersionsByDatasetId operation.
	//
	// List dataset versions.
	//
	// GET /v1/datasets/{id}/versions
	ListDatasetVersionsByDatasetId(ctx context.Context, params ListDatasetVersionsByDatasetIdParams) (ListDatasetVersionsByDatasetIdRes, error)
	// ListDatasets implements listDatasets operation.
	//
	// List datasets.
	//
	// GET /v1/datasets
	ListDatasets(ctx context.Context, params ListDatasetsParams) (ListDatasetsRes, error)
	// ListExperimentRuns implements listExperimentRuns operation.
	//
	// Retrieve a paginated list of runs for an experiment.
	//
	// GET /v1/experiments/{experiment_id}/runs
	ListExperimentRuns(ctx context.Context, params ListExperimentRunsParams) (ListExperimentRunsRes, error)
	// ListExperiments implements listExperiments operation.
	//
	// Retrieve a paginated list of experiments for the specified dataset.
	//
	// GET /v1/datasets/{dataset_id}/experiments
	ListExperiments(ctx context.Context, params ListExperimentsParams) (ListExperimentsRes, error)
	// ListPromptVersions implements listPromptVersions operation.
	//
	// Retrieve all versions of a specific prompt with pagination support. Each prompt can have multiple
	// versions with different configurations.
	//
	// GET /v1/prompts/{prompt_identifier}/versions
	ListPromptVersions(ctx context.Context, params ListPromptVersionsParams) (ListPromptVersionsRes, error)
	// ListSessionAnnotationsBySessionIds implements listSessionAnnotationsBySessionIds operation.
	//
	// Get session annotations for a list of session_ids.
	//
	// GET /v1/projects/{project_identifier}/session_annotations
	ListSessionAnnotationsBySessionIds(ctx context.Context, params ListSessionAnnotationsBySessionIdsParams) (ListSessionAnnotationsBySessionIdsRes, error)
	// ListSpanAnnotationsBySpanIds implements listSpanAnnotationsBySpanIds operation.
	//
	// Get span annotations for a list of span_ids.
	//
	// GET /v1/projects/{project_identifier}/span_annotations
	ListSpanAnnotationsBySpanIds(ctx context.Context, params ListSpanAnnotationsBySpanIdsParams) (ListSpanAnnotationsBySpanIdsRes, error)
	// ListTraceAnnotationsByTraceIds implements listTraceAnnotationsByTraceIds operation.
	//
	// Get trace annotations for a list of trace_ids.
	//
	// GET /v1/projects/{project_identifier}/trace_annotations
	ListTraceAnnotationsByTraceIds(ctx context.Context, params ListTraceAnnotationsByTraceIdsParams) (ListTraceAnnotationsByTraceIdsRes, error)
	// PostPromptVersion implements postPromptVersion operation.
	//
	// Create a new prompt and its initial version. A prompt can have multiple versions.
	//
	// POST /v1/prompts
	PostPromptVersion(ctx context.Context, req *CreatePromptRequestBody) (PostPromptVersionRes, error)
	// UpdateAnnotationConfigV1AnnotationConfigsConfigIDPut implements update_annotation_config_v1_annotation_configs__config_id__put operation.
	//
	// Update an annotation configuration.
	//
	// PUT /v1/annotation_configs/{config_id}
	UpdateAnnotationConfigV1AnnotationConfigsConfigIDPut(ctx context.Context, req CreateAnnotationConfigData, params UpdateAnnotationConfigV1AnnotationConfigsConfigIDPutParams) (UpdateAnnotationConfigV1AnnotationConfigsConfigIDPutRes, error)
	// UpdateProject implements updateProject operation.
	//
	// Update an existing project with new configuration. Project names cannot be changed. The project
	// identifier is either project ID or project name. Note: When using a project name as the identifier,
	//  it cannot contain slash (/), question mark (?), or pound sign (#) characters.
	//
	// PUT /v1/projects/{project_identifier}
	UpdateProject(ctx context.Context, req *UpdateProjectRequestBody, params UpdateProjectParams) (UpdateProjectRes, error)
	// UploadDataset implements uploadDataset operation.
	//
	// Upload dataset from JSON, CSV, or PyArrow.
	//
	// POST /v1/datasets/upload
	UploadDataset(ctx context.Context, req UploadDatasetReq, params UploadDatasetParams) (UploadDatasetRes, error)
	// UpsertExperimentEvaluation implements upsertExperimentEvaluation operation.
	//
	// Create or update evaluation for an experiment run.
	//
	// POST /v1/experiment_evaluations
	UpsertExperimentEvaluation(ctx context.Context, req *UpsertExperimentEvaluationRequestBody) (UpsertExperimentEvaluationRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
