// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddEvaluations implements addEvaluations operation.
//
// Add span, trace, or document evaluations.
//
// POST /v1/evaluations
func (UnimplementedHandler) AddEvaluations(ctx context.Context, req AddEvaluationsReq, params AddEvaluationsParams) (r AddEvaluationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AnnotateSessions implements annotateSessions operation.
//
// Create session annotations.
//
// POST /v1/session_annotations
func (UnimplementedHandler) AnnotateSessions(ctx context.Context, req *AnnotateSessionsRequestBody, params AnnotateSessionsParams) (r AnnotateSessionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AnnotateSpanDocuments implements annotateSpanDocuments operation.
//
// Annotate Span Documents.
//
// POST /v1/document_annotations
func (UnimplementedHandler) AnnotateSpanDocuments(ctx context.Context, req *AnnotateSpanDocumentsRequestBody, params AnnotateSpanDocumentsParams) (r AnnotateSpanDocumentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AnnotateSpans implements annotateSpans operation.
//
// Create span annotations.
//
// POST /v1/span_annotations
func (UnimplementedHandler) AnnotateSpans(ctx context.Context, req *AnnotateSpansRequestBody, params AnnotateSpansParams) (r AnnotateSpansRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AnnotateTraces implements annotateTraces operation.
//
// Create trace annotations.
//
// POST /v1/trace_annotations
func (UnimplementedHandler) AnnotateTraces(ctx context.Context, req *AnnotateTracesRequestBody, params AnnotateTracesParams) (r AnnotateTracesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAnnotationConfigV1AnnotationConfigsPost implements create_annotation_config_v1_annotation_configs_post operation.
//
// Create an annotation configuration.
//
// POST /v1/annotation_configs
func (UnimplementedHandler) CreateAnnotationConfigV1AnnotationConfigsPost(ctx context.Context, req CreateAnnotationConfigData) (r CreateAnnotationConfigV1AnnotationConfigsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateExperiment implements createExperiment operation.
//
// Create experiment on a dataset.
//
// POST /v1/datasets/{dataset_id}/experiments
func (UnimplementedHandler) CreateExperiment(ctx context.Context, req *CreateExperimentRequestBody, params CreateExperimentParams) (r CreateExperimentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateExperimentRun implements createExperimentRun operation.
//
// Create run for an experiment.
//
// POST /v1/experiments/{experiment_id}/runs
func (UnimplementedHandler) CreateExperimentRun(ctx context.Context, req *CreateExperimentRunRequestBody, params CreateExperimentRunParams) (r CreateExperimentRunRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProject implements createProject operation.
//
// Create a new project with the specified configuration.
//
// POST /v1/projects
func (UnimplementedHandler) CreateProject(ctx context.Context, req *CreateProjectRequestBody) (r CreateProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePromptVersionTag implements createPromptVersionTag operation.
//
// Add a new tag to a specific prompt version. Tags help identify and categorize different versions
// of a prompt.
//
// POST /v1/prompt_versions/{prompt_version_id}/tags
func (UnimplementedHandler) CreatePromptVersionTag(ctx context.Context, req *PromptVersionTagData, params CreatePromptVersionTagParams) (r CreatePromptVersionTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSpanNote implements createSpanNote operation.
//
// Add a note annotation to a span. Notes are special annotations that allow multiple entries per
// span (unlike regular annotations which are unique by name and identifier). Each note gets a unique
// timestamp-based identifier.
//
// POST /v1/span_notes
func (UnimplementedHandler) CreateSpanNote(ctx context.Context, req *CreateSpanNoteRequestBody) (r CreateSpanNoteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSpans implements createSpans operation.
//
// Submit spans to be inserted into a project. If any spans are invalid or duplicates, no spans will
// be inserted.
//
// POST /v1/projects/{project_identifier}/spans
func (UnimplementedHandler) CreateSpans(ctx context.Context, req *CreateSpansRequestBody, params CreateSpansParams) (r CreateSpansRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements createUser operation.
//
// Create a new user with the specified configuration.
//
// POST /v1/users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *CreateUserRequestBody) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAnnotationConfigV1AnnotationConfigsConfigIDDelete implements delete_annotation_config_v1_annotation_configs__config_id__delete operation.
//
// Delete an annotation configuration.
//
// DELETE /v1/annotation_configs/{config_id}
func (UnimplementedHandler) DeleteAnnotationConfigV1AnnotationConfigsConfigIDDelete(ctx context.Context, params DeleteAnnotationConfigV1AnnotationConfigsConfigIDDeleteParams) (r DeleteAnnotationConfigV1AnnotationConfigsConfigIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDatasetById implements deleteDatasetById operation.
//
// Delete dataset by ID.
//
// DELETE /v1/datasets/{id}
func (UnimplementedHandler) DeleteDatasetById(ctx context.Context, params DeleteDatasetByIdParams) (r DeleteDatasetByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteExperiment implements deleteExperiment operation.
//
// Delete experiment by ID.
//
// DELETE /v1/experiments/{experiment_id}
func (UnimplementedHandler) DeleteExperiment(ctx context.Context, params DeleteExperimentParams) (r DeleteExperimentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteProject implements deleteProject operation.
//
// Delete an existing project and all its associated data. The project identifier is either project
// ID or project name. The default project cannot be deleted. Note: When using a project name as the
// identifier, it cannot contain slash (/), question mark (?), or pound sign (#) characters.
//
// DELETE /v1/projects/{project_identifier}
func (UnimplementedHandler) DeleteProject(ctx context.Context, params DeleteProjectParams) (r DeleteProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSpan implements deleteSpan operation.
//
// Delete a single span by identifier.
// **Important**: This operation deletes ONLY the specified span itself and does NOT
// delete its descendants/children. All child spans will remain in the trace and
// become orphaned (their parent_id will point to a non-existent span).
// Behavior:
// - Deletes only the target span (preserves all descendant spans)
// - If this was the last span in the trace, the trace record is also deleted
// - If the deleted span had a parent, its cumulative metrics (error count, token counts)
// are subtracted from all ancestor spans in the chain
// **Note**: This operation is irreversible and may create orphaned spans.
//
// DELETE /v1/spans/{span_identifier}
func (UnimplementedHandler) DeleteSpan(ctx context.Context, params DeleteSpanParams) (r DeleteSpanRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTrace implements deleteTrace operation.
//
// Delete an entire trace by its identifier. The identifier can be either:
// 1. A Relay node ID (base64-encoded)
// 2. An OpenTelemetry trace_id (hex string)
// This will permanently remove all spans in the trace and their associated data.
//
// DELETE /v1/traces/{trace_identifier}
func (UnimplementedHandler) DeleteTrace(ctx context.Context, params DeleteTraceParams) (r DeleteTraceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUser implements deleteUser operation.
//
// Delete an existing user by their unique GlobalID.
//
// DELETE /v1/users/{user_id}
func (UnimplementedHandler) DeleteUser(ctx context.Context, params DeleteUserParams) (r DeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAnnotationConfigByNameOrIDV1AnnotationConfigsConfigIdentifierGet implements get_annotation_config_by_name_or_id_v1_annotation_configs__config_identifier__get operation.
//
// Get an annotation configuration by ID or name.
//
// GET /v1/annotation_configs/{config_identifier}
func (UnimplementedHandler) GetAnnotationConfigByNameOrIDV1AnnotationConfigsConfigIdentifierGet(ctx context.Context, params GetAnnotationConfigByNameOrIDV1AnnotationConfigsConfigIdentifierGetParams) (r GetAnnotationConfigByNameOrIDV1AnnotationConfigsConfigIdentifierGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDataset implements getDataset operation.
//
// Get dataset by ID.
//
// GET /v1/datasets/{id}
func (UnimplementedHandler) GetDataset(ctx context.Context, params GetDatasetParams) (r GetDatasetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatasetCsv implements getDatasetCsv operation.
//
// Download dataset examples as CSV file.
//
// GET /v1/datasets/{id}/csv
func (UnimplementedHandler) GetDatasetCsv(ctx context.Context, params GetDatasetCsvParams) (r GetDatasetCsvRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatasetExamples implements getDatasetExamples operation.
//
// Get examples from a dataset.
//
// GET /v1/datasets/{id}/examples
func (UnimplementedHandler) GetDatasetExamples(ctx context.Context, params GetDatasetExamplesParams) (r GetDatasetExamplesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatasetJSONLOpenAIEvals implements getDatasetJSONLOpenAIEvals operation.
//
// Download dataset examples as OpenAI evals JSONL file.
//
// GET /v1/datasets/{id}/jsonl/openai_evals
func (UnimplementedHandler) GetDatasetJSONLOpenAIEvals(ctx context.Context, params GetDatasetJSONLOpenAIEvalsParams) (r GetDatasetJSONLOpenAIEvalsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatasetJSONLOpenAIFineTuning implements getDatasetJSONLOpenAIFineTuning operation.
//
// Download dataset examples as OpenAI fine-tuning JSONL file.
//
// GET /v1/datasets/{id}/jsonl/openai_ft
func (UnimplementedHandler) GetDatasetJSONLOpenAIFineTuning(ctx context.Context, params GetDatasetJSONLOpenAIFineTuningParams) (r GetDatasetJSONLOpenAIFineTuningRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEvaluations implements getEvaluations operation.
//
// Get span, trace, or document evaluations from a project.
//
// GET /v1/evaluations
func (UnimplementedHandler) GetEvaluations(ctx context.Context, params GetEvaluationsParams) (r GetEvaluationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExperiment implements getExperiment operation.
//
// Get experiment by ID.
//
// GET /v1/experiments/{experiment_id}
func (UnimplementedHandler) GetExperiment(ctx context.Context, params GetExperimentParams) (r GetExperimentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExperimentCSV implements getExperimentCSV operation.
//
// Download experiment runs as a CSV file.
//
// GET /v1/experiments/{experiment_id}/csv
func (UnimplementedHandler) GetExperimentCSV(ctx context.Context, params GetExperimentCSVParams) (r GetExperimentCSVRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExperimentJSON implements getExperimentJSON operation.
//
// Download experiment runs as a JSON file.
//
// GET /v1/experiments/{experiment_id}/json
func (UnimplementedHandler) GetExperimentJSON(ctx context.Context, params GetExperimentJSONParams) (r GetExperimentJSONRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIncompleteExperimentEvaluations implements getIncompleteExperimentEvaluations operation.
//
// Get experiment runs that have incomplete evaluations.
// Returns runs with:
// - Missing evaluations (evaluator has not been run)
// - Failed evaluations (evaluator ran but has errors)
// Args:
// experiment_id: The ID of the experiment
// evaluation_name: List of evaluation names to check (required, at least one)
// cursor: Cursor for pagination
// limit: Maximum number of results to return
// Returns:
// Paginated list of runs with incomplete evaluations.
//
// GET /v1/experiments/{experiment_id}/incomplete-evaluations
func (UnimplementedHandler) GetIncompleteExperimentEvaluations(ctx context.Context, params GetIncompleteExperimentEvaluationsParams) (r GetIncompleteExperimentEvaluationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIncompleteExperimentRuns implements getIncompleteExperimentRuns operation.
//
// Get runs that need to be completed for this experiment.
// Returns all incomplete runs, including both missing runs (not yet attempted)
// and failed runs (attempted but have errors).
// Args:
// experiment_id: The ID of the experiment
// cursor: Cursor for pagination
// limit: Maximum number of results to return
// Returns:
// Paginated list of incomplete runs grouped by dataset example,
// with repetition numbers that need to be run.
//
// GET /v1/experiments/{experiment_id}/incomplete-runs
func (UnimplementedHandler) GetIncompleteExperimentRuns(ctx context.Context, params GetIncompleteExperimentRunsParams) (r GetIncompleteExperimentRunsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProject implements getProject operation.
//
// Retrieve a specific project using its unique identifier: either project ID or project name. Note:
// When using a project name as the identifier, it cannot contain slash (/), question mark (?), or
// pound sign (#) characters.
//
// GET /v1/projects/{project_identifier}
func (UnimplementedHandler) GetProject(ctx context.Context, params GetProjectParams) (r GetProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjects implements getProjects operation.
//
// Retrieve a paginated list of all projects in the system.
//
// GET /v1/projects
func (UnimplementedHandler) GetProjects(ctx context.Context, params GetProjectsParams) (r GetProjectsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPromptVersionByPromptVersionId implements getPromptVersionByPromptVersionId operation.
//
// Retrieve a specific prompt version using its unique identifier. A prompt version contains the
// actual template and configuration.
//
// GET /v1/prompt_versions/{prompt_version_id}
func (UnimplementedHandler) GetPromptVersionByPromptVersionId(ctx context.Context, params GetPromptVersionByPromptVersionIdParams) (r GetPromptVersionByPromptVersionIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPromptVersionByTagName implements getPromptVersionByTagName operation.
//
// Retrieve a specific prompt version using its tag name. Tags are used to identify specific versions
// of a prompt.
//
// GET /v1/prompts/{prompt_identifier}/tags/{tag_name}
func (UnimplementedHandler) GetPromptVersionByTagName(ctx context.Context, params GetPromptVersionByTagNameParams) (r GetPromptVersionByTagNameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPromptVersionLatest implements getPromptVersionLatest operation.
//
// Retrieve the most recent version of a specific prompt.
//
// GET /v1/prompts/{prompt_identifier}/latest
func (UnimplementedHandler) GetPromptVersionLatest(ctx context.Context, params GetPromptVersionLatestParams) (r GetPromptVersionLatestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPromptVersionTags implements getPromptVersionTags operation.
//
// Retrieve all tags associated with a specific prompt version. Tags are used to identify and
// categorize different versions of a prompt.
//
// GET /v1/prompt_versions/{prompt_version_id}/tags
func (UnimplementedHandler) GetPromptVersionTags(ctx context.Context, params GetPromptVersionTagsParams) (r GetPromptVersionTagsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPrompts implements getPrompts operation.
//
// Retrieve a paginated list of all prompts in the system. A prompt can have multiple versions.
//
// GET /v1/prompts
func (UnimplementedHandler) GetPrompts(ctx context.Context, params GetPromptsParams) (r GetPromptsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpans implements getSpans operation.
//
// Return spans within a project filtered by time range. Supports cursor-based pagination.
//
// GET /v1/projects/{project_identifier}/spans
func (UnimplementedHandler) GetSpans(ctx context.Context, params GetSpansParams) (r GetSpansRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsers implements getUsers operation.
//
// Retrieve a paginated list of all users in the system.
//
// GET /v1/users
func (UnimplementedHandler) GetUsers(ctx context.Context, params GetUsersParams) (r GetUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAnnotationConfigsV1AnnotationConfigsGet implements list_annotation_configs_v1_annotation_configs_get operation.
//
// Retrieve a paginated list of all annotation configurations in the system.
//
// GET /v1/annotation_configs
func (UnimplementedHandler) ListAnnotationConfigsV1AnnotationConfigsGet(ctx context.Context, params ListAnnotationConfigsV1AnnotationConfigsGetParams) (r ListAnnotationConfigsV1AnnotationConfigsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDatasetVersionsByDatasetId implements listDatasetVersionsByDatasetId operation.
//
// List dataset versions.
//
// GET /v1/datasets/{id}/versions
func (UnimplementedHandler) ListDatasetVersionsByDatasetId(ctx context.Context, params ListDatasetVersionsByDatasetIdParams) (r ListDatasetVersionsByDatasetIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDatasets implements listDatasets operation.
//
// List datasets.
//
// GET /v1/datasets
func (UnimplementedHandler) ListDatasets(ctx context.Context, params ListDatasetsParams) (r ListDatasetsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListExperimentRuns implements listExperimentRuns operation.
//
// Retrieve a paginated list of runs for an experiment.
//
// GET /v1/experiments/{experiment_id}/runs
func (UnimplementedHandler) ListExperimentRuns(ctx context.Context, params ListExperimentRunsParams) (r ListExperimentRunsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListExperiments implements listExperiments operation.
//
// Retrieve a paginated list of experiments for the specified dataset.
//
// GET /v1/datasets/{dataset_id}/experiments
func (UnimplementedHandler) ListExperiments(ctx context.Context, params ListExperimentsParams) (r ListExperimentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPromptVersions implements listPromptVersions operation.
//
// Retrieve all versions of a specific prompt with pagination support. Each prompt can have multiple
// versions with different configurations.
//
// GET /v1/prompts/{prompt_identifier}/versions
func (UnimplementedHandler) ListPromptVersions(ctx context.Context, params ListPromptVersionsParams) (r ListPromptVersionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSessionAnnotationsBySessionIds implements listSessionAnnotationsBySessionIds operation.
//
// Get session annotations for a list of session_ids.
//
// GET /v1/projects/{project_identifier}/session_annotations
func (UnimplementedHandler) ListSessionAnnotationsBySessionIds(ctx context.Context, params ListSessionAnnotationsBySessionIdsParams) (r ListSessionAnnotationsBySessionIdsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSpanAnnotationsBySpanIds implements listSpanAnnotationsBySpanIds operation.
//
// Get span annotations for a list of span_ids.
//
// GET /v1/projects/{project_identifier}/span_annotations
func (UnimplementedHandler) ListSpanAnnotationsBySpanIds(ctx context.Context, params ListSpanAnnotationsBySpanIdsParams) (r ListSpanAnnotationsBySpanIdsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTraceAnnotationsByTraceIds implements listTraceAnnotationsByTraceIds operation.
//
// Get trace annotations for a list of trace_ids.
//
// GET /v1/projects/{project_identifier}/trace_annotations
func (UnimplementedHandler) ListTraceAnnotationsByTraceIds(ctx context.Context, params ListTraceAnnotationsByTraceIdsParams) (r ListTraceAnnotationsByTraceIdsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostPromptVersion implements postPromptVersion operation.
//
// Create a new prompt and its initial version. A prompt can have multiple versions.
//
// POST /v1/prompts
func (UnimplementedHandler) PostPromptVersion(ctx context.Context, req *CreatePromptRequestBody) (r PostPromptVersionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAnnotationConfigV1AnnotationConfigsConfigIDPut implements update_annotation_config_v1_annotation_configs__config_id__put operation.
//
// Update an annotation configuration.
//
// PUT /v1/annotation_configs/{config_id}
func (UnimplementedHandler) UpdateAnnotationConfigV1AnnotationConfigsConfigIDPut(ctx context.Context, req CreateAnnotationConfigData, params UpdateAnnotationConfigV1AnnotationConfigsConfigIDPutParams) (r UpdateAnnotationConfigV1AnnotationConfigsConfigIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProject implements updateProject operation.
//
// Update an existing project with new configuration. Project names cannot be changed. The project
// identifier is either project ID or project name. Note: When using a project name as the identifier,
//
//	it cannot contain slash (/), question mark (?), or pound sign (#) characters.
//
// PUT /v1/projects/{project_identifier}
func (UnimplementedHandler) UpdateProject(ctx context.Context, req *UpdateProjectRequestBody, params UpdateProjectParams) (r UpdateProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadDataset implements uploadDataset operation.
//
// Upload dataset from JSON, CSV, or PyArrow.
//
// POST /v1/datasets/upload
func (UnimplementedHandler) UploadDataset(ctx context.Context, req UploadDatasetReq, params UploadDatasetParams) (r UploadDatasetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpsertExperimentEvaluation implements upsertExperimentEvaluation operation.
//
// Create or update evaluation for an experiment run.
//
// POST /v1/experiment_evaluations
func (UnimplementedHandler) UpsertExperimentEvaluation(ctx context.Context, req *UpsertExperimentEvaluationRequestBody) (r UpsertExperimentEvaluationRes, _ error) {
	return r, ht.ErrNotImplemented
}
