// Code generated by ogen, DO NOT EDIT.
package api

type AddEvaluationsReq interface {
	addEvaluationsReq()
}

type AddEvaluationsRes interface {
	addEvaluationsRes()
}

type AnnotateSessionsRes interface {
	annotateSessionsRes()
}

type AnnotateSpanDocumentsRes interface {
	annotateSpanDocumentsRes()
}

type AnnotateSpansRes interface {
	annotateSpansRes()
}

type AnnotateTracesRes interface {
	annotateTracesRes()
}

type CreateAnnotationConfigV1AnnotationConfigsPostRes interface {
	createAnnotationConfigV1AnnotationConfigsPostRes()
}

type CreateExperimentRes interface {
	createExperimentRes()
}

type CreateExperimentRunRes interface {
	createExperimentRunRes()
}

type CreateProjectRes interface {
	createProjectRes()
}

type CreatePromptVersionTagRes interface {
	createPromptVersionTagRes()
}

type CreateSpanNoteRes interface {
	createSpanNoteRes()
}

type CreateSpansRes interface {
	createSpansRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteAnnotationConfigV1AnnotationConfigsConfigIDDeleteRes interface {
	deleteAnnotationConfigV1AnnotationConfigsConfigIDDeleteRes()
}

type DeleteDatasetByIdRes interface {
	deleteDatasetByIdRes()
}

type DeleteExperimentRes interface {
	deleteExperimentRes()
}

type DeleteProjectRes interface {
	deleteProjectRes()
}

type DeleteSpanRes interface {
	deleteSpanRes()
}

type DeleteTraceRes interface {
	deleteTraceRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type GetAnnotationConfigByNameOrIDV1AnnotationConfigsConfigIdentifierGetRes interface {
	getAnnotationConfigByNameOrIDV1AnnotationConfigsConfigIdentifierGetRes()
}

type GetDatasetCsvRes interface {
	getDatasetCsvRes()
}

type GetDatasetExamplesRes interface {
	getDatasetExamplesRes()
}

type GetDatasetJSONLOpenAIEvalsRes interface {
	getDatasetJSONLOpenAIEvalsRes()
}

type GetDatasetJSONLOpenAIFineTuningRes interface {
	getDatasetJSONLOpenAIFineTuningRes()
}

type GetDatasetRes interface {
	getDatasetRes()
}

type GetEvaluationsRes interface {
	getEvaluationsRes()
}

type GetExperimentCSVRes interface {
	getExperimentCSVRes()
}

type GetExperimentJSONRes interface {
	getExperimentJSONRes()
}

type GetExperimentRes interface {
	getExperimentRes()
}

type GetIncompleteExperimentEvaluationsRes interface {
	getIncompleteExperimentEvaluationsRes()
}

type GetIncompleteExperimentRunsRes interface {
	getIncompleteExperimentRunsRes()
}

type GetProjectRes interface {
	getProjectRes()
}

type GetProjectsRes interface {
	getProjectsRes()
}

type GetPromptVersionByPromptVersionIdRes interface {
	getPromptVersionByPromptVersionIdRes()
}

type GetPromptVersionByTagNameRes interface {
	getPromptVersionByTagNameRes()
}

type GetPromptVersionLatestRes interface {
	getPromptVersionLatestRes()
}

type GetPromptVersionTagsRes interface {
	getPromptVersionTagsRes()
}

type GetPromptsRes interface {
	getPromptsRes()
}

type GetSpansRes interface {
	getSpansRes()
}

type GetUsersRes interface {
	getUsersRes()
}

type ListAnnotationConfigsV1AnnotationConfigsGetRes interface {
	listAnnotationConfigsV1AnnotationConfigsGetRes()
}

type ListDatasetVersionsByDatasetIdRes interface {
	listDatasetVersionsByDatasetIdRes()
}

type ListDatasetsRes interface {
	listDatasetsRes()
}

type ListExperimentRunsRes interface {
	listExperimentRunsRes()
}

type ListExperimentsRes interface {
	listExperimentsRes()
}

type ListPromptVersionsRes interface {
	listPromptVersionsRes()
}

type ListSessionAnnotationsBySessionIdsRes interface {
	listSessionAnnotationsBySessionIdsRes()
}

type ListSpanAnnotationsBySpanIdsRes interface {
	listSpanAnnotationsBySpanIdsRes()
}

type ListTraceAnnotationsByTraceIdsRes interface {
	listTraceAnnotationsByTraceIdsRes()
}

type PostPromptVersionRes interface {
	postPromptVersionRes()
}

type UpdateAnnotationConfigV1AnnotationConfigsConfigIDPutRes interface {
	updateAnnotationConfigV1AnnotationConfigsConfigIDPutRes()
}

type UpdateProjectRes interface {
	updateProjectRes()
}

type UploadDatasetReq interface {
	uploadDatasetReq()
}

type UploadDatasetRes interface {
	uploadDatasetRes()
}

type UpsertExperimentEvaluationRes interface {
	upsertExperimentEvaluationRes()
}
