// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CreateExperimentRequestBody) setDefaults() {
	{
		val := int(1)
		s.Repetitions.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateUserRequestBody) setDefaults() {
	{
		val := bool(true)
		s.SendWelcomeEmail.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SessionAnnotation) setDefaults() {
	{
		val := string("")
		s.Identifier.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SessionAnnotationData) setDefaults() {
	{
		val := string("")
		s.Identifier.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Span) setDefaults() {
	{
		val := string("")
		s.ID.SetTo(val)
	}
	{
		val := string("")
		s.StatusMessage.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SpanAnnotation) setDefaults() {
	{
		val := string("")
		s.Identifier.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SpanAnnotationData) setDefaults() {
	{
		val := string("")
		s.Identifier.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SpanDocumentAnnotationData) setDefaults() {
	{
		val := string("")
		s.Identifier.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TraceAnnotation) setDefaults() {
	{
		val := string("")
		s.Identifier.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TraceAnnotationData) setDefaults() {
	{
		val := string("")
		s.Identifier.SetTo(val)
	}
}
